defmodule FunSheepWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :fun_sheep

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_fun_sheep_key",
    signing_salt: "TEdUeeYM",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # Assets under /assets are content-addressed (phx.digest appends a hash),
  # so they can be cached indefinitely. Other static files (fonts, images, etc.)
  # use default headers and are not marked immutable.
  plug Plug.Static,
    at: "/assets",
    from: {:fun_sheep, "priv/static"},
    gzip: not code_reloading?,
    headers: %{"cache-control" => "public, max-age=31536000, immutable"}

  plug Plug.Static,
    at: "/",
    from: :fun_sheep,
    gzip: not code_reloading?,
    only: FunSheepWeb.static_paths() -- ["assets"],
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :fun_sheep
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 50_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FunSheepWeb.Plugs.MaintenanceMode
  plug FunSheepWeb.Router
end
