defmodule Mix.Tasks.Funsheep.Sections.Regenerate do
  @shortdoc "Re-generate granular concept sections for all chapters in a course"

  @moduledoc """
  Enqueues SectionRegenerationWorker jobs for every chapter in a course.

  Chapters that already have >= 4 non-default sections are skipped by the
  worker itself. Chapters with only an "Overview" section (the default
  fallback) get a proper concept breakdown generated by AI. After new
  sections are created, questions from the old "Overview" section are
  reset to :uncategorized so QuestionClassificationWorker re-tags them
  against the new granular concepts.

  ## Usage

      mix funsheep.sections.regenerate --course-id COURSE_UUID

  The task only enqueues Oban jobs — sections are generated asynchronously
  as the :ai queue processes each chapter. Watch the worker logs for progress.

  To check status afterward:

      # How many chapters still need sections?
      select count(*) from chapters c
      left join sections s on s.chapter_id = c.id
      where c.course_id = '...' and s.id is null;

      # How many questions are awaiting re-classification?
      select count(*) from questions
      where course_id = '...' and classification_status = 'uncategorized';
  """

  use Mix.Task

  alias FunSheep.Courses
  alias FunSheep.Workers.SectionRegenerationWorker

  @switches [course_id: :string]

  @impl Mix.Task
  def run(argv) do
    Mix.Task.run("app.start")
    {opts, _, _} = OptionParser.parse(argv, switches: @switches)

    course_id = Keyword.get(opts, :course_id) || Mix.raise("Required: --course-id COURSE_UUID")

    course = Courses.get_course!(course_id)

    Mix.shell().info(
      "Regenerating sections for: #{course.name} (#{course.subject}, grade #{course.grade})"
    )

    {:ok, count} = SectionRegenerationWorker.enqueue_for_course(course_id)

    Mix.shell().info(
      "Enqueued #{count} jobs into the :ai queue. Chapters with >= 4 existing sections will be skipped automatically."
    )
  end
end
