import Config

# Configure your database
config :fun_sheep, FunSheep.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5434,
  database: "fun_sheep_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fun_sheep, FunSheepWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4040")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "MtqIVM1HmKPqeOqb7R2xHT6SkzZCdzhOyCgTJVYIE1TEmaqXHvVHEq5N24+ea9RX",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:fun_sheep, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:fun_sheep, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :fun_sheep, FunSheepWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/fun_sheep_web/router\.ex$",
      ~r"lib/fun_sheep_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :fun_sheep, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Interactor configuration (mock mode for development)
config :fun_sheep,
  interactor_mock: false,
  interactor_url: System.get_env("INTERACTOR_URL", "http://localhost:4001"),
  interactor_core_url: System.get_env("INTERACTOR_CORE_URL", "https://core.interactor.com"),
  interactor_ukb_url: "http://localhost:4005",
  interactor_udb_url: "http://localhost:4007",
  interactor_org_name: System.get_env("INTERACTOR_ORG_NAME", "studysmart"),
  interactor_client_id: System.get_env("INTERACTOR_CLIENT_ID", "app_Pp4JCBlFXxIoADX1kv41"),
  interactor_client_secret:
    System.get_env(
      "INTERACTOR_CLIENT_SECRET",
      "sec_Ar5o5Nca_o3lxBk0ujelnB2RGyYgE97n4-2gP72i-MC8"
    )

# Storage backend
config :fun_sheep, :storage_backend, FunSheep.Storage.Local

# OCR configuration
config :fun_sheep, :ocr_mock, false
# Google Vision API key is loaded at runtime from .env.credentials (see runtime.exs)
